apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: YOUR-TOWER-HOST-NAME
      http:
        paths:
          - path: /*
            backend:
              serviceName: frontend
              servicePort: 80
