site_name: "Tower User Documentation"
site_author: Seqera Labs
repo_name: nf-tower-docs
repo_url: https://github.com/seqeralabs/nf-tower-docs
edit_uri: https://github.com/seqeralabs/nf-tower-docs/tree/master/docs

site_dir: public

plugins:
  - social
  - search
#   - git-revision-date
#   - git-revision-date-localized:
#       fallback_to_build_date: true

theme:
  language: en
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: white
  favicon: _favicons/favicon.ico
  logo: _logos/nf-tower-icon-black.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  font: false
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
  - stylesheets/fonts.css
  - stylesheets/overrides.css
  - stylesheets/extra.css # 2022-04-01 Added by Graham to get more space above bullets.

extra:
  analytics:
    provider: google
    property: G-NR1CNM213G
  # generator: false
  homepage: /
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@seqera.io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/seqeralabs
    - icon: fontawesome/brands/github
      link: https://github.com/seqeralabs
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Home": "index.md"
  - "Getting started":
      - "Usage": "getting-started/usage.md"
      - "Deployment options": "getting-started/deployment-options.md"
      - "Workspaces": "getting-started/workspace.md"
  - "Core concepts": "core-concepts/definitions.md"
  - "Users & workspaces":
      - "Overview": "orgs-and-teams/overview.md"
      - "Organizations": "orgs-and-teams/organizations.md"
      - "Workspace management": "orgs-and-teams/workspace-management.md"
      - "Shared workspaces": "orgs-and-teams/shared-workspaces.md"
      - "User and organization administration": "administration/overview.md"
  - "Launching pipelines":
      - "Launchpad": "launch/launchpad.md"
      - "Launch form": "launch/launch.md"
      - "Advanced options": "launch/advanced.md"
      - "Relaunch": "launch/relaunch.md"
      - "Notifications": "launch/notifications.md"
  - "Monitoring pipelines":
      - "Overview": "monitoring/overview.md"
      - "Dashboard": "dashboard/overview.md"
      - "Execution details & logs": "monitoring/execution.md"
      - "Summary & status": "monitoring/summary.md"
      - "Processes": "monitoring/processes.md"
      - "Aggregate stats & load": "monitoring/aggregate_stats.md"
      - "Tasks & metrics": "monitoring/tasks.md"
    # - 'Sharing pipelines': 'monitoring/sharing.md'
  - "Compute environments":
      - "Overview": "compute-envs/overview.md"
      - "AWS Batch": "compute-envs/aws-batch.md"
      - "Azure Batch": "compute-envs/azure-batch.md"
      - "Google Cloud Batch": "compute-envs/google-cloud-batch.md"
      - "Google Life Sciences": "compute-envs/google-cloud-lifesciences.md"
      - "Altair Grid Engine": "compute-envs/altair-grid-engine.md"
      - "Altair PBS Pro": "compute-envs/altair-pbs-pro.md"
      - "IBM LSF": "compute-envs/lsf.md"
      - "Moab": "compute-envs/moab.md"
      - "Slurm": "compute-envs/slurm.md"
      - "Kubernetes": "compute-envs/k8s.md"
      - "Amazon EKS": "compute-envs/eks.md"
      - "Google GKE": "compute-envs/gke.md"
  - "Credentials":
      - "Overview": "credentials/overview.md"
      - "Container registry credentials":
          - "AWS Elastic Container Registry": "credentials/aws_registry_credentials.md"
          - "Azure Container Registry": "credentials/azure_registry_credentials.md"
          - "Docker Hub": "credentials/docker_hub_registry_credentials.md"
          - "Google Cloud Artifact Registry": "credentials/google_registry_credentials.md"
          - "Quay": "credentials/quay_registry_credentials.md"
  - "Datasets": "datasets/overview.md"
  - "Git integration": "git/overview.md"
  - "Labels": "labels/overview.md"
  - "Resource labels": "resource-labels/overview.md"
  - "Pipeline actions": "pipeline-actions/overview.md"
  - "Pipeline reports": "reports/overview.md"
  - "Pipeline schema": "pipeline-schema/overview.md"
  - "Pipeline secrets": "secrets/overview.md"
  - "Tower limits": "limits/limits.md"
  - "Tower Agent": "agent.md"
  - "API": "api/overview.md"
  - "tw CLI": "cli.md"
  - "Supported software":
      - "Illumina DRAGEN": "supported_software/dragen/overview.md"
      - "Tower Agent": "agent.md"
      - "Fusion file system": "supported_software/fusion/fusion.md"
  - "Data privacy": data-privacy/overview.md
  - "Functionality matrix": "functionality_matrix/functionality_matrix.md"
  - "FAQs and troubleshooting": faqs.md

copyright: Copyright &copy; 2019 - 2023 Seqera Labs, S.L.
