site_name: Nextflow Tower documentation
site_author: Seqera Labs
repo_name: nf-tower-docs
repo_url: https://github.com/seqeralabs/nf-tower-docs
edit_uri: https://github.com/seqeralabs/nf-tower-docs/tree/master/docs

site_dir: public

plugins:
- social
- search
#   - git-revision-date
#   - git-revision-date-localized:
#       fallback_to_build_date: true

theme:
  language: en
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: white
  favicon: _favicons/favicon.ico
  logo: _logos/nf-tower-icon-black.svg
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  font: false


extra_css:
- stylesheets/fonts.css
- stylesheets/overrides.css
- stylesheets/extra.css   # 2022-04-01 Added by Graham to get more space above bullets.

extra:
  analytics:
    provider: google
    property: G-NR1CNM213G
  # generator: false
  homepage: /
  social:
  - icon: fontawesome/solid/paper-plane
    link: mailto:support@seqera.io
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/seqeralabs
  - icon: fontawesome/brands/github
    link: https://github.com/seqeralabs
  version:
    provider: mike

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
- toc:
    permalink: '#'
- attr_list
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    linenums: true
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list

nav:
- Home: index.md
- Releases:
  - Changelog: enterprise/release_notes/changelog.md
  - Functionality matrix: functionality_matrix/functionality_matrix.md
  - '23.1': enterprise/release_notes/23.1.md
  - '22.4': enterprise/release_notes/22.4.md
  - '22.3': enterprise/release_notes/22.3.md
  - '22.2': enterprise/release_notes/22.2.md
  - '22.1': enterprise/release_notes/22.1.md
  - '21.12': enterprise/release_notes/21.12.md
  - '21.10': enterprise/release_notes/21.10.md
  - '21.06': enterprise/release_notes/21.06.md
  - '21.04': enterprise/release_notes/21.04.md
  - '21.02': enterprise/release_notes/21.02.md
  #- '20.12': enterprise/release_notes/20.12.md
  #- '20.10': enterprise/release_notes/20.10.md
  #- '20.08': enterprise/release_notes/20.08.md
  #- '20.06': enterprise/release_notes/20.06.md
- Getting started:
  - Core concepts: core-concepts/definitions.md
  - Usage: getting-started/usage.md
  - Deployment options: getting-started/deployment-options.md
  - Workspaces: getting-started/workspace.md
- User guide:
  - Users & workspaces:
    - Overview: orgs-and-teams/overview.md
    - Organizations: orgs-and-teams/organizations.md
    - Workspace management: orgs-and-teams/workspace-management.md
    - Shared workspaces: orgs-and-teams/shared-workspaces.md
    - User and organization administration: administration/overview.md
  - Launching pipelines:
    - Launchpad: launch/launchpad.md
    - Launch form: launch/launch.md
    - Advanced options: launch/advanced.md
    - Re-launching pipelines: launch/relaunch.md
    - Notifications: launch/notifications.md
  - Monitoring pipelines:
    - Overview: monitoring/overview.md
    - Dashboard: dashboard/overview.md
    - Execution details & logs: monitoring/execution.md
    - Summary & status: monitoring/summary.md
    - Processes: monitoring/processes.md
    - Aggregate stats & load: monitoring/aggregate_stats.md
    - Tasks & metrics: monitoring/tasks.md
      # - 'Sharing pipelines': 'monitoring/sharing.md'
  - Compute environments:
    - Overview: compute-envs/overview.md
    - HPC clusters: compute-envs/hpc.md
    - AWS Batch: compute-envs/aws-batch.md
    - Azure Batch: compute-envs/azure-batch.md
    - Google Cloud Batch: compute-envs/google-cloud-batch.md
    - Google Life Sciences: compute-envs/google-cloud-lifesciences.md
        #- "Altair Grid Engine": "compute-envs/altair-grid-engine.md"
        #- "Altair PBS Pro": "compute-envs/altair-pbs-pro.md"
        #- "IBM LSF": "compute-envs/lsf.md"
        #- "Moab": "compute-envs/moab.md"
        #- "Slurm": "compute-envs/slurm.md"
    - Kubernetes: compute-envs/k8s.md
    - Amazon EKS: compute-envs/eks.md
    - Google GKE: compute-envs/gke.md
  - Credentials:
    - Overview: credentials/overview.md
    - Container registry credentials:
      - AWS Elastic Container Registry: credentials/aws_registry_credentials.md
      - Azure Container Registry: credentials/azure_registry_credentials.md
      - Docker Hub: credentials/docker_hub_registry_credentials.md
      - Google Cloud: credentials/google_registry_credentials.md
      - Quay: credentials/quay_registry_credentials.md
    - SSH credentials: credentials/ssh_credentials.md
    - Tower Agent credentials: credentials/agent_credentials.md
  - Datasets: datasets/overview.md
  - Git integration: git/overview.md
  - Labels: 
    - Tower labels: labels/overview.md
    - Resource labels: resource-labels/overview.md
  - Pipeline actions: pipeline-actions/overview.md
  - Pipeline reports: reports/overview.md
  - Pipeline schema: pipeline-schema/overview.md
  - Pipeline secrets: secrets/overview.md
- Installation guide:
  - Introduction: enterprise/index.md
  - Configuration:
    - Overview: enterprise/configuration/overview.md
    - Authentication: enterprise/configuration/authentication.md
    - Compute Environments: enterprise/configuration/compute_environments.md
    - Git Integration: enterprise/configuration/git_integration.md
    - Mail Server: enterprise/configuration/mail_server.md
    - Networking: enterprise/configuration/networking.md
    - SSL/TLS: enterprise/configuration/ssl_tls.md
    - Tower and Redis Databases: enterprise/configuration/database_and_redis.md
    - Tower API: enterprise/configuration/tower_api.md
    - Wave containers: enterprise/configuration/wave.md
  - Prerequisites:
    - AWS: enterprise/prerequisites/aws.md
    - Azure: enterprise/prerequisites/azure.md
    - GCP: enterprise/prerequisites/gcp.md
    - On-prem: enterprise/prerequisites/on-prem.md
  - Docker Compose: enterprise/docker-compose.md
  - Kubernetes: enterprise/kubernetes.md
  - Advanced topics:
    - Configure AWS Batch manually: enterprise/advanced-topics/manual-aws-batch-setup.md
    - Deploy to AWS CloudFormation: enterprise/advanced-topics/cloudformation.md
    - Migrate Docker database to RDS: enterprise/advanced-topics/db-docker-to-RDS.md
    - Use custom launch container: enterprise/advanced-topics/custom-launch-container.md
    - Legacy Tower container images: enterprise/advanced-topics/tower-container-images.md
    - Use IAM role instead of user credentials: enterprise/advanced-topics/use-iam-role.md
  - Troubleshooting: enterprise/general_troubleshooting.md
- Developer tools:
  - API: api/overview.md
  - tw CLI: cli.md
- Software integration:
  - Tower Agent: agent.md
  - Fusion file system: supported_software/fusion/fusion.md
  - Illumina DRAGEN: supported_software/dragen/overview.md
- Reference:
  - Data privacy: data-privacy/overview.md
  - Usage limits: limits/limits.md
- FAQs and troubleshooting: faqs.md

copyright: Copyright &copy; 2019 - 2023 Seqera Labs, S.L.
