# Simple local volume scratch storage 
# Only works for a single node cluster
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tower-storage
spec:
  storageClassName: scratch
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/tower
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tower-scratch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: scratch
...