version: "3"
services:
  db:
    image: mysql:5.7
    networks:
      - backend
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    volumes:
      # The passwords inside this init script must match with those defined in the .env files.
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      # Enable this snippet to store the Mysql data in a directory on the host
      # - $HOME/.tower/db/mysql:/var/lib/mysql

  redis:
    image: cr.seqera.io/public/redis:5.0.8
    networks:
      - backend
    expose:
      - 6379
    command: --appendonly yes
    restart: always
    # Enable this snippet to store the Redis data in a directory on the host
    # volumes:
    #   - $HOME/.tower/db/redis:/data

  cron:
    image: cr.seqera.io/private/nf-tower-enterprise/backend:v23.1.3
    command: -c '/wait-for-it.sh db:3306 -t 60; /migrate-db.sh; /tower.sh'
    networks:
      - backend
    volumes:
      - $PWD/tower.yml:/tower.yml
    env_file:
      - tower.env
    environment:
      - MICRONAUT_ENVIRONMENTS=prod,redis,cron
    restart: always
    depends_on:
      - db
      - redis

  backend:
    image: cr.seqera.io/private/nf-tower-enterprise/backend:v23.1.3
    command: -c '/wait-for-it.sh db:3306 -t 60; /tower.sh'
    networks:
      - frontend
      - backend
    expose:
      - 8080
    volumes:
      - $PWD/tower.yml:/tower.yml
    env_file:
      - tower.env
    environment:
      - MICRONAUT_ENVIRONMENTS=prod,redis,ha
      # Uncomment the following if groundswell needs to be enabled and delete
      # the MICRONAUT_ENVIRONMENTS variable above.
      #- MICRONAUT_ENVIRONMENTS=prod,redis,ha,groundswell
      #- GROUNDSWELL_SERVER_URL="http://groundswell:8090"
    restart: always
    depends_on:
      - db
      - redis
      - cron

  frontend:
    image: cr.seqera.io/private/nf-tower-enterprise/frontend:v23.1.3
    networks:
      - frontend
    ports:
      - 8000:80
    restart: always
    depends_on:
      - backend

  # Uncomment the following section to enable the groundswell service.
  # groundswell:
  #   image: cr.seqera.io/private/nf-tower-enterprise/groundswell:0.3.3
  #   command: bash -c 'bin/wait-for-it.sh db:3306 -t 60; bin/migrate-db.sh; bin/serve.sh'
  #   networks:
  #     - backend
  #   ports:
  #     - 8090:8090
  #   env_file:
  #     - groundswell.env
  #   restart: always
  #   depends_on:
  #     - db

networks:
  frontend: {}
  backend: {}
