CREATE DATABASE IF NOT EXISTS `tower`;
CREATE DATABASE IF NOT EXISTS `swell`;
CREATE USER 'tower'@'%' IDENTIFIED BY 'tower';
CREATE USER 'swell'@'%' IDENTIFIED BY 'swell';
GRANT ALL PRIVILEGES ON *.* TO 'tower'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'swell'@'%';
FLUSH PRIVILEGES;
