#NOTE: Used https://github.com/jimporter/mike/issues/49 as a reference for designing this custom solution
#TODO: Allow the latest version to be picked up from the commit string

name: Build and deploy staging-html

on:
  push:
    branches:
      - staging
      - github-action

jobs:
  mkdocs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          # git-revision-date-localized-plugin and mkdocs-rss-plugin need full git history depth
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.9.7"
          cache: 'pip'

      - name: Set up git author
        #        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/v')
        run: |
          git config --global user.name "ci-bot"
          git config --global user.email "ci-bot@seqera.io"
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git remote rm origin
          git remote add origin "${remote_repo}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip setuptools wheel
          # python -m pip install mike
          pip install -r requirements.txt
          python -m pip install "git+https://${{ secrets.GITEA_TOKEN }}@git.seqera.io/seqeralabs/mkdocs-material-insiders@7.3.3-insiders-3.1.3"


      - name: Build staging-html using mike
        run: |
          mike deploy -b staging-html --update-aliases 22.3 latest


      - name: Add Netlify _redirects file to staging-html 
        run: |
          git switch staging-html
          echo "/*   /latest/:splat   404" > _redirects
          git add _redirects
          git commit -m "publish latest version with updated _redirects file"
          git push -u origin staging-html --force
          # mike set-default latest -b staging-html
